---
development:
  cloud_name: dpz4maiv4
  api_key: '425599574597193'
  api_secret: 1I_JWWGqko5tG6Lsj9wRVkMGV8U
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dpz4maiv4
  api_key: '425599574597193'
  api_secret: 1I_JWWGqko5tG6Lsj9wRVkMGV8U
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dpz4maiv4
  api_key: '425599574597193'
  api_secret: 1I_JWWGqko5tG6Lsj9wRVkMGV8U
  enhance_image_tag: true
  static_file_support: false
